version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/BSAWeatherApp"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
